config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :books, :tags
  root to: "books#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    validates :title, presence: true
    validates :author, presence: true
    validates :year, presence: true
    validates :description, presence: true
    validates :cover, presence: true, blob: { content_type: :image }
    validates :content, presence: true, blob: { content_type: 'application/pdf' }

    has_one_attached :cover
    has_one_attached :content

    has_one :tag
    accepts_nested_attributes_for :tag

    def self.search(query)
        where("title like ? or author like ?", "%#{query}%", "%#{query}%")
    end

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :book
  validates :semester, presence: true
  validates :course, presence: true
  validates :others, presence: true
  validates :degree, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: %i[ show ]

  @@per_page_pagination = 16

  def index
    if params[:search]
      @books = Book.search(params[:search])
      .paginate(:page => params[:page], per_page: @@per_page_pagination)
    else
      @books = Book.all
      .paginate(:page => params[:page], per_page: @@per_page_pagination)
    end
  end

  def show
  end

  def new
    @book = Book.new
    @book.build_tag
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  private
   
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :year, :description, :cover, :content, :tag_attributes => [:semester, :course, :others, :degree])
    end
    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

  end

  private

    def tag_params
      params.require(:tag).permit(:semester, :course, :others, :degree, :book_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<% content_for :content do %>

  <br/>

  <div id="search_field">
    <%= bootstrap_form_tag url: '/', method: :get do |f| %>
        <%= f.text_field :search, hide_label: true, placeholder: 'Search for book\'s titles or authors' %>
    <% end %>
  </div>

  <br/>

  <div id = "container">
    <% @books.each do |book| %>
    <a class = "books" href= <%= url_for(book) %> >
      <section class= "info">
        <img src = <%= url_for(book.cover) %> alt="book_cover"> 
        <div class="content">
          <h3><%= book.title %></h3>
          <h4><%= book.author %></h4>
        </div>
      </a>
    </section>
    <% end %>
  </div>

  <br>

  <div class="mt-3 d-flex justify-content-center">
	  <%= will_paginate @books %>
  </div>

<% end %>

app/views/books/new.html.erb
<% content_for :content do %>

    <div class="text-center">
        
        <br/><h2>New Book</h2><br/>

        <%= bootstrap_form_for(@book, class: 'text-right') do |f| %>

            <div class = "same-line">

                <div class = "initial-infos">
                    <%= f.text_field :title %><br/>
                    <%= f.text_field :author %><br/>
                    <%= f.number_field :year %><br/>
                </div>

                <div class = "large-text">
                    <%= f.text_area :description %><br/>
                </div>
            
            </div>

            <div class = "same-line">

            <%= f.fields_for :tag do |t|%>
                <div>
                    <%= t.select :semester, [["1", "first"], ["2", "second"], ["3", "third"], ["4", "fourth"],
                    ["5", "fifth"], ["6", "sixth"], ["7", "seventh"], ["8", "eighth"], 
                    ["9", "ninth"], ["10", "tenth"]] %>
                    <br/>
                    <%= t.text_field :course %><br/>
                </div>
                <div>
                    <%= t.select :degree, [["bachelor", "bachelor"], ["lincenciature", "licenciature"]] %>
                    <br/>
                    <%= t.text_field :others %><br/>
                </div>
            <% end %>

            </div>

            <%= f.label :photo %>
            <%= f.file_field :cover, hide_label: true %><br/>
            <%= f.label :document %>
            <%= f.file_field :content, hide_label: true %><br/>


            <div class="d-flex justify-content-center col">
                    <%= f.submit "Create" %>
            </div>

	    <% end %>
    
        <br/>

    </div>
    
<% end %>

app/views/books/show.html.erb
<% content_for :content do %>

  <div class = "book_title">
    <br/> <h1 style="text-align:center"><%= @book.title %></h1>
    <br/> <h2 style="text-align:center"><%= @book.author %></h1> <br/>
  </div>

  <div id = "book_info">

    <div class = "about">

      <section id="book's_cover">
        <img src = <%= url_for(@book.cover) %> alt="book_cover">
      </section>

      <section class="info_section">
        <strong>Year:</strong>
        <%= @book.year %>
      </section>

      <section class="info_section">
        <strong>Description:</strong>
        <%= @book.description %>
      </section>

      <section class="info_section">
        <strong>Semester:</strong>
        <%= @book.tag.semester %>
      </section>

      <section class="info_section">
        <strong>Course:</strong>
        <%= @book.tag.course %>
      </section>

      <section class="info_section">
        <strong>Others:</strong>
        <%= @book.tag.others %>
      </section>

      <section class="info_section">
        <strong>Degree:</strong>
        <%= @book.tag.degree %>
      </section>
      
    </div>

    <div class = "book_content">
      <iframe src=<%= url_for(@book.content) %> width="600" height="780" style="border: none;"> </iframe>
    </div> 

  </div>

<% end %>

app/views/layouts/_navigation.html.erb
<a class="text-color-clear" href="/" style="text-decoration:none">
    <nav class="navbar navbar-expand-sm navbar-dark navbar-fixed-top color-navbar">
        <nav class="pl-2">
            <img src="<%= asset_path('book-stack.png') %>" width="25" height="25" class="mt-2 mr-1 d-inline-block align-top" style="-webkit-filter: invert(100%) !important;" alt="">
            <b class="navbar-brand">
                e-Library
            </b>	
        </nav>
</a>

<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav text-color-clear no-text-decoration">									
        <%= link_to 'Add book', new_book_path , class: 'nav-item nav-link text-white' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <title>e-Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'books', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('book-stack.png') %>

  </head>

  <body>
    <%= yield %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>